// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozmmrojzpiiaylsijptg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96bW1yb2p6cGlpYXlsc2lqcHRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MDgzNTEsImV4cCI6MjA1OTE4NDM1MX0.UXted35fDLfk24l_9QHbQuoku9I6FUlKyU1J0oGYLGU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);